INSERT INTO massage (Titre, Type, DescriptionCourte, Description, Duree, Prix, Image, Displayed, Rang)
VALUES
    ('Réflexologie plantaire', null, 'Massage curatif','Un toucher spécifique appliqué sur les zones réflexes permet de localiser des tensions et autres dysfonctionnements. L''activation de certains points par simple pression permet d''agir sur les organes en déséquilibre ou encrassés afin d''améliorer leur état ou les redynamiser.', '01:00:00', 49, '/public/assets/massage-05.jpg', true, 1),
    ('Californien', 'à l''huile', 'Massage bien-être','Le massage californien est une approche globale qui vise autant la détente que l''éveil d''une conscience psychocorporelle. Ce massage utilise de longs mouvements lents et fluides qui permettent une profonde relaxation physique et psychique.', '01:00:00', 49, '/public/assets/massage-03.jpg', true, 2),
    ('Suédois', 'à l''huile', 'Massage curatif','Souvent considéré comme la forme la plus classique des approches corporelles, Ie massage suédois est une technique de massage dynamique qui vise à dissoudre les tensions et à raffermir les muscles et les articulations. Son effet tonifiant et relaxant favorise la circulation sanguine et lymphatique et l’élimination des toxines, et aide le corps à retrouver son équilibre naturel.', '01:00:00', 49, '/public/assets/massage-03.jpg', true, 3),
    ('Dos', 'à l''huile', 'Massage bien-être','Le massage du dos vise principalement la détente et la relaxation. Il permet également d''évacuer les toxines et de stimuler la circulation sanguine, lymphatique et énergétique.', '00:30:00', 30, '/public/assets/massage-03.jpg', true, 4),
    ('Jambes', 'à l''huile', 'Massage curatif','Ce massage vise une détente des muscles et des tendons mais aussi une amélioration de la circulation sanguine et lympathique.', '00:30:00', 30, '/public/assets/massage-04.jpg', true, 5),
    ('Visage, épaules et crane + pierres froides', 'à l''huile', 'Massage bien-être','Ce massage permet de détendre tout le corps en stimulant les points réflexes situés sur les zones du visage, du cuir chevelu, des oreilles, de la nuque et du haut des épaules. Contrairement à un massage intégral, quelques instants suffisent pour commencer à se détendre.', '00:20:00', 20, '/public/assets/massage-02.jpg', true, 6),
    ('Pierres chaudes', 'à l''huile', 'Massage bien-être','La chaleur dégagée par les pierres favorise la détente et la relaxation. Cette technique soulage les contractures, avec un effet drainant et apaisant. Elle permet de stimuler le système lymphatique et la circulation sanguine, tout en atténuant les douleurs musculaires et articulaires.', '01:20:00', 59, '/public/assets/stephane-yaich-olM1XPcPsTg-unsplash.jpg', true, 7),
    ('Shiatsu', 'oriental', 'Massage bien-être','Réputé pour ses vertus purifiantes, relaxantes et son action libératrice sur les terminaisons nerveuses et les muscles, le massage oriental apporte une réelle sensation de bien-être profond. En plus de ces bienfaits sur l’esprit et le corps, le rituel est excellent pour la qualité et la beauté de l’épiderme. La peau est plus souple, plus douce, plus lisse.', '01:00:00', 49, '/public/assets/massage-03.jpg', true, 8),
    ('Amma assis', 'oriental', 'Massage curatif','Le massage AMMA assis est un technique avec des gestes de pressions, d’étirements, de percussions et de balayages qui permet de soulager les douleurs et à détendre le dos, les épaules, les bras, les mains, la tête et la nuque.', '00:30:00', 30, '/public/assets/massage-02.jpg',true,9);


